branch-defaults:
  dev/eb_aws_deploy:
    environment: cafepedia-dev
global:
  application_name: cafepedia
  branch: null
  default_ec2_keyname: eb_cafepedia
  default_platform: Ruby 2.4 (Puma)
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
